image: node:6.9.4

pipelines:
  branches:
    test:
        - step:
            script: # Modify the commands below to build your repository.
              - apt-get update && apt-get install -y python-dev
              - apt-get install -y zip # required for packaging up the application
              - curl -O https://bootstrap.pypa.io/get-pip.py
              - python get-pip.py
              - pip install boto3==1.3.0 # required for beanstalk_deploy.py
              - npm install # install vue and all relevant components
              - npm run build -- 2
              - cd dist
              - zip -r /tmp/artifact.zip * # package up the application for deployment
              - cd ..
              - python beanstalk_deploy_test.py # run the deployment script
    master:
        - step:
            script: # Modify the commands below to build your repository.
              - apt-get update && apt-get install -y python-dev
              - apt-get install -y zip # required for packaging up the application
              - curl -O https://bootstrap.pypa.io/get-pip.py
              - python get-pip.py
              - pip install boto3==1.3.0 # required for beanstalk_deploy.py
              - npm install # install vue and all relevant components
              - npm run build -- 2
              - cd dist
              - zip -r /tmp/artifact.zip * # package up the application for deployment
              - cd ..
              - python beanstalk_deploy.py # run the deployment script